name: Docker Image CI

on:
  push: # push 时触发ci
    branches: [main] # 作用于main分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取main分支代码
      - name: Checkout
        uses: actions/checkout@v2

      # 制作docker镜像并推送到阿里云容器镜像服务
      - name: build and push docker image
        run: |
          echo waste199794 | docker login  --username=820016771@qq.com registry.cn-beijing.aliyuncs.com --password-stdin
          docker image build -t ${{secrets.ALIYUN_DOCKER_PROJECT_NAME}}:latest .
          docker tag ${{secrets.ALIYUN_DOCKER_PROJECT_NAME}} registry.cn-beijing.aliyuncs.com/waste_97/vue-project:latest
          docker push ${{secrets.ALIYUN_DOCKER_IMAGES}}/${{secrets.ALIYUN_DOCKER_PROJECT_NAME}}:latest
          docker logout
      # 登录远程服务器，拉取镜像，制作并重启容器
      # https://github.com/marketplace/actions/remote-ssh-commands
      - name: ssh remote deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /
            echo -e "1.docker login start==>"
            echo ${{ secrets.ALIYUN_DOCKER_PASSWORD }} | docker login --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin

            echo -e "2.docker stop myblog container==>"
            docker container stop ${{secrets.ALIYUN_DOCKER_PROJECT_NAME}}

            echo -e "3.docker conatainer rm==>"
            docker container rm ${{secrets.ALIYUN_DOCKER_PROJECT_NAME}}

            echo -e "4.docker image rm==>"
            docker image rm ${{secrets.ALIYUN_DOCKER_IMAGES}}/${{secrets.ALIYUN_DOCKER_PROJECT_NAME}}:latest

            echo -e "5.docker pull==>"
            docker pull ${{secrets.ALIYUN_DOCKER_IMAGES}}/${{secrets.ALIYUN_DOCKER_PROJECT_NAME}}:latest

            echo -e "6.docker container create and start==>"
            docker container run -d -p 80:80 --name ${{secrets.ALIYUN_DOCKER_PROJECT_NAME}} ${{secrets.ALIYUN_DOCKER_PROJECT_NAME}}:latest

            echo -e "7.docker logout==>"
            docker logout
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASSWORD }}
